spring:
  datasource:
    url: jdbc:mysql://152.136.29.128:3306/scholar
    username: root
    password: 7427f7796d988436
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto=update


  mail:
    host: smtp.163.com
    port:
    username: buaa_tech@163.com
    password: GAQPXBEZGFAPGBXJ
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  jpa:
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml

server:
  port: 8001

swagger:
  enable: true
  application-name: demo
  application-version: 1.0
  try-host: http://localhost:${server.port}