spring:
  datasource:
    url: jdbc:mysql://81.70.9.149/scholar
    username: root
    password: zousijie1994_Z
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml

server:
  port: 8001

swagger:
  enable: true
  application-name: demo
  application-version: 1.0
  try-host: http://localhost:${server.port}