spring:
  datasource:
    url: jdbc:mysql://81.70.9.149/scholar
    username: root
    password: zousijie1994_Z
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.163.com
    port:
    username: buaa_tech@163.com
    password: GAQPXBEZGFAPGBXJ
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml

server:
  port: 8001

swagger:
  enable: true
  application-name: demo
  application-version: 1.0
  try-host: http://localhost:${server.port}